# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'ReactNativeVersioningExample' do

end



target 'ReactNativeVersioningExample-tvOS' do

end

target 'ReactNativeVersioningExample-tvOSTests' do

end

